CREATE TABLE MEMBER
(
    MEMBERID   NUMBER                 NOT NULL,
    NAME      VARCHAR2(30)           NOT NULL,
    EMAIL      VARCHAR2(50)           NOT NULL,
    PASSWORD   VARCHAR2(130)          NOT NULL,
    SALT       VARCHAR2(64)           NOT NULL,
    CONTACT    VARCHAR2(15)           NOT NULL,
    QUESTION   VARCHAR2(200)          NOT NULL,
    ANSWER     VARCHAR2(200)          NOT NULL,
    REGDATE    DATE   DEFAULT SYSDATE NOT NULL,
    REMAINTIME NUMBER DEFAULT 0       NOT NULL
);

CREATE SEQUENCE MEMBERID_SEQ;

BEGIN
    FOR i IN 1..300 LOOP
        INSERT INTO MEMBER VALUES (PCMASTER.MEMBERID_SEQ.NEXTVAL, 'testtest', 'test@test.com', 'testtesttest', 'test1234', '123-1234-1234', 'test', 'test', SYSDATE, 0);
    END LOOP;
END;
