DROP TABLE ORDER;

CREATE TABLE ORDER
(
    ORDERID   INT
        CONSTRAINT PK_ORDER PRIMARY KEY,
    QUANTITY  INT               NOT NULL,
    ORDERDATE DATE DEFAULT SYSDATE NOT NULL,
    STOCKID   INT               NOT NULL
);

ALTER TABLE ORDER
    ADD CONSTRAINT FK_STOCK_TO_ORDER_1 FOREIGN KEY (STOCKID)
        REFERENCES STOCK (STOCKID);

DROP SEQUENCE ORDERID_SEQ;

CREATE SEQUENCE ORDERID_SEQ;
