DROP TABLE IF EXISTS PRODUCT_STOCK

CREATE TABLE PRODUCT_STOCK
(
    PRODUCTID INT,
    STOCKID   INT,
    PRIMARY KEY (PRODUCTID, STOCKID),
    FOREIGN KEY (PRODUCTID) REFERENCES PRODUCT (PRODUCTID),
    FOREIGN KEY (STOCKID) REFERENCES STOCK (STOCKID)
);
