DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE PRODUCT
(
    PRODUCTID   INT
        CONSTRAINT PK_PRODUCT PRIMARY KEY,
    PRODUCTNAME VARCHAR2(30) NOT NULL,
    CATEGORY    VARCHAR2(30) NOT NULL,
    PRICE       INT   NOT NULL,
    STOCK       INT   NOT NULL
);

DROP SEQUENCE IF EXISTS PRODUCTID_SEQ;

CREATE SEQUENCE PRODUCTID_SEQ;
