DROP TABLE SALE;

CREATE TABLE SALE
(
    SALEID     INT
        CONSTRAINT PK_SALE PRIMARY KEY,
    QUANTITY   INT                  NOT NULL,
    TOTALPRICE INT                  NOT NULL,
    SALEDATE   DATE DEFAULT SYSDATE NOT NULL,
    PRODUCTID  INT                  NOT NULL,
    MEMBERID   INT                  NOT NULL
);

ALTER TABLE SALE
    ADD CONSTRAINT FK_MEMBER_SALE FOREIGN KEY (MEMBERID)
        REFERENCES MEMBER (MEMBERID);

ALTER TABLE SALE
    ADD CONSTRAINT FK_PRODUCT_SALE FOREIGN KEY (PRODUCTID)
        REFERENCES PRODUCT (PRODUCTID);

DROP SEQUENCE SALEID_SEQ;

CREATE SEQUENCE SALEID_SEQ;
